let studentName = "Ihor";
let surname = "Stefaniv";
let group = "654JS";
let birght = "19.03.1996";
let merriedStatus = false;
let age = 25;
let child = null;

console.log(age);
console.log(typeof age);
console.log(birght);
console.log(typeof birght);
console.log(merriedStatus);
console.log(typeof merriedStatus);
console.log(studentName);
console.log(typeof studentName);
console.log(surname);
console.log(typeof surname);
console.log(group);
console.log(typeof group);
console.log(child);
console.log(typeof child);