let name = "Ihor";
console.log(name);
console.log(typeof name);
let surname = "Stefaniv";
console.log(surname);
console.log(typeof surname);
let group = "654JS";
console.log(group);
console.log(typeof group);
let birght = "19.03.1996";
console.log(birght);
console.log(typeof surbirghtname);
let merriedStatus = false;
console.log(merriedStatus);
console.log(typeof merriedStatus);
let age = 25;
console.log(age);
console.log(typeof age);
let child = null;
console.log(child);
console.log(typeof child);